# Обработка ошибок, "try..catch"

## Синтаксис «try…catch»

Конструкция `try..catch` состоит из двух основных блоков: `try`, и затем `catch`.

Работает она так: 

1. Сначала выполняется код внутри блока `try {...}`.
2. Если в нём нет ошибок, то блок `catch(err)` игнорируется: выполнение доходит до конца `try` и потом далее, полностью пропуская `catch`.
3. Если же в нём возникает ошибка, то выполнение `try` прерывается, и поток управления переходит в начало `catch(err)`. Переменная `err` (можно использовать любое имя) содержит объект ошибки с подробной информацией о произошедшем.

Т.о., при ошибке в блоке `try` скрипт не падает, и нас есть возможность обработать ошибку внутри `catch`

### `try..catch` работает только для ошибок, возникающих во время выполнения кода

Чтобы `try..catch` работал, код должен быть выполнимым. Другими словами, это должен быть корректный JS-код. 

Он не сработает, если код синтаксически неверен. JS-движок сначала читает код, а затем исполняет его. Ошибки, которые возникают во время фазы чтения, называются ошибками парсинга.

### `try..catch` работает синхронно 

Исключение, которое произойдет в коде, запланнированном "на будущее", например в `setTimeout`, `try..catch` не поймает

## Объект ошибки

- `name`

 Имя ошибки. Например, для неопределённой переменной это `"ReferenceError"`.

 - `message`

 Текстовое сообщение о деталях ошибки.
 В большинстве окружений доступны и другие, нестандартные свойства. Одно из самых широко используемых и поддерживаемых – это:

- `stack`

Текущий стек вызова: строка, содержащая информацию о последовательности вложенных вызовов, которые привели к ошибке. Используется в целях отладки.

## Блок «catch» без переменной

Эта возможность была добавлена в язык недавно. В старых браузерах может понадобиться полифил.

Если нам не нужны детали ошибки, в catch можно её пропустить.

## Оператор «throw»

Оператор `throw` генерирует ошибку

Технически в качестве объекта ошибки можно передать что угодно. Это может быть даже примитив, число или строка, но всё же лучше, чтобы это был объект, желательно со свойствами `name` и `message`.

В JavaScript есть множество встроенных конструкторов для стандартных ошибок: `Error`, `SyntaxError`, `ReferenceError`, `TypeError` и другие. Можно использовать и их для создания объектов ошибки.

## Проброс исключения

Блок `catch` должен обрабатывать только те ошибки, которые ему известны, и «пробрасывать» все остальные.

Техника «проброс исключения» выглядит так:

1. Блок catch получает все ошибки.
2. В блоке` catch(err) {...}` мы анализируем объект ошибки `err`.
3. Если мы не знаем как её обработать, тогда делаем throw `err`.